name: Test BOOT_SIGN_KEY

on: [push]

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check BOOT_SIGN_KEY
        env:
          BOOT_SIGN_KEY: ${{ secrets.BOOT_SIGN_KEY }}
        run: |
          if [ -n "$BOOT_SIGN_KEY" ]; then
            echo "BOOT_SIGN_KEY is set."
          else
            echo "Error: BOOT_SIGN_KEY is not set."
            exit 1
          fi
